/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get offers for a customer reference
         * @description Resolves third-party offers and maps them to a stable frontend response.
         */
        get: operations["getOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorResponse: {
            /** @enum {string} */
            errorCode: "INVALID_REQUEST" | "INTERNAL_ERROR" | "INVALID_UPSTREAM_RESPONSE" | "UPSTREAM_UNAVAILABLE";
            requestId: string;
        };
        GetOffersResponse: {
            offers: components["schemas"]["Offer"][];
            /** @enum {string} */
            source: "other-service";
        };
        Offer: {
            id: string;
            title: string;
            monthlyPrice: components["schemas"]["Money"];
            highlights: string[];
        };
        Money: {
            /** @example 19.99 */
            amount: string;
            /** @example EUR */
            currency: string;
        };
    };
    responses: {
        /** @description The frontend request is missing required or valid input. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description The BFF is not configured correctly or failed unexpectedly. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description The upstream returned a response that violates its expected contract. */
        InvalidUpstreamResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description The upstream timed out, rate-limited the request, or was unavailable. */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOffers: {
        parameters: {
            query: {
                /**
                 * @description Fictional opaque reference used only for this request.
                 * @example demo-123
                 */
                customerReference: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers were resolved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOffersResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
            502: components["responses"]["InvalidUpstreamResponse"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
}
